import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Relogio from "@/components/Relogio";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const data = new Date();

  return (
    <html lang="en">
      <body className="flex flex-col justify-start gap-4 p-20 items-center min-h-screen">

        {/* HEADER */}
        <header className="flex flex-col items-center">
          <h1>React & Next.js</h1>

          <nav className="flex gap-4">
            <Link href="/">Intro</Link>
            <Link href="/sobre">Sobre</Link>
            <Link href="/tecnologias">Tecnologias</Link>
            <Link href="/caracteristicas">Características</Link>
            <Link href="/projetos">Projetos</Link>
            <Link href="/contador">Contador</Link>
            <Link href="/input">Input</Link>
            <Link href="/produtos">Produtos</Link>
          </nav>
        </header>

        {/* MAIN */}
        <main className="bg-violet-700 p-5 rounded-2xl max-w-2xl min-h-[70vh]">
          {children}
        </main>

        {/* FOOTER */}
        <footer className="flex flex-col items-center gap-2">
          <span>DIW {data.getFullYear()}</span>
          <Relogio />
        </footer>

      </body>
    </html>
  );
}

